In [0]:
import numpy as np

In [0]:
student_score = [
 [1, 90, 80, 85, 0, 0.0, 0, 0],
 [2, 88, 85, 90, 0, 0.0, 0, 0],
 [3, 32, 85, 90, 0, 0.0, 0, 0],
 [4, 42, 75, 93, 0, 0.0, 0, 0],
 [5, 82, 86, 88, 0, 0.0, 0, 0]
]
ndarray = np.array(student_score)
ndarray, type(ndarray), type(ndarray[0])

(array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
        [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
        [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
        [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
        [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]]),
 numpy.ndarray,
 numpy.ndarray)

## Indexing & Slicing

In [0]:
ndarray[:, 0], ndarray[4, :], ndarray[:, 1:4]

(array([1., 2., 3., 4., 5.]),
 array([ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]),
 array([[90., 80., 85.],
        [88., 85., 90.],
        [32., 85., 90.],
        [42., 75., 93.],
        [82., 86., 88.]]))

## Statistic

In [0]:
np.max(ndarray[:, 0],axis=0), np.sum(ndarray[:,1:4],axis=1)

(5.0, array([255., 263., 207., 210., 256.]))

In [0]:
ndarray[:, 4] = np.sum(ndarray[:,1:4],axis=1)
ndarray, type(ndarray), ndarray.shape

(array([[  1.,  90.,  80.,  85., 255.,   0.,   0.,   0.],
        [  2.,  88.,  85.,  90., 263.,   0.,   0.,   0.],
        [  3.,  32.,  85.,  90., 207.,   0.,   0.,   0.],
        [  4.,  42.,  75.,  93., 210.,   0.,   0.,   0.],
        [  5.,  82.,  86.,  88., 256.,   0.,   0.,   0.]]),
 numpy.ndarray,
 (5, 8))

##Broadcasting

In [0]:
x = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [4, 5, 6]])
x, x.shape, x.ndim

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]), (4, 3), 2)

In [0]:
x + 0.4

array([[0.4, 1.4, 2.4],
       [1.4, 2.4, 3.4],
       [2.4, 3.4, 4.4],
       [4.4, 5.4, 6.4]])

In [0]:
x * [0,1,0.1]

array([[0. , 1. , 0.2],
       [0. , 2. , 0.3],
       [0. , 3. , 0.4],
       [0. , 5. , 0.6]])

## 조건연산(True, False)

In [0]:
(ndarray == 0), (ndarray[:,1:5] > 20), (ndarray[:,1:5] > 20) & (ndarray[:,1:5] > 80)

(array([[False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True],
        [False, False, False, False, False,  True,  True,  True]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ True, False,  True,  True],
        [ True,  True,  True,  True],
        [False,  True,  True,  True],
        [False, False,  True,  True],
        [ True,  True,  True,  True]]))

## Mask

In [0]:
ndarray[(ndarray == 0)]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# same Mask ndarray size
ndarr = ndarray[:,1:5]
ndarr[(ndarr > 20)]

array([ 90.,  80.,  85., 255.,  88.,  85.,  90., 263.,  32.,  85.,  90.,
       207.,  42.,  75.,  93., 210.,  82.,  86.,  88., 256.])

# Insert & delete

In [0]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]]) 
np.insert(a,1,[11,12,13],axis = 0), np.insert(a,2,11,axis = 1)

(array([[ 1,  2,  3],
        [11, 12, 13],
        [ 3,  4,  5],
        [ 5,  6,  7]]), array([[ 1,  2, 11,  3],
        [ 3,  4, 11,  5],
        [ 5,  6, 11,  7]]))

In [21]:
np.delete(a,1,axis = 1), np.delete(a,[0,2],axis = 0)

(array([[1, 3],
        [3, 5],
        [5, 7]]), array([[3, 4, 5]]))