In [0]:
import numpy as np

In [0]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8],[9,10]])

In [0]:
a

array([[1, 2],
       [3, 4]])

In [0]:
b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [0]:
np.concatenate((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [0]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [0]:
np.concatenate((a,b), axis = 1)

ValueError: ignored

In [0]:
a = np.arange(9)
b = np.split(a,3,axis=0)
a, type(a), b, type(b)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 numpy.ndarray,
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])],
 list)

In [0]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
np.insert(a,1,[11,11],axis=0)

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [0]:
np.insert(a,2,11,axis=1)

array([[ 1,  2, 11],
       [ 3,  4, 11],
       [ 5,  6, 11]])

In [0]:
b = [[11,12],[13,14]]

In [0]:
np.insert(a,1,b,axis=0)

array([[ 1,  2],
       [11, 12],
       [13, 14],
       [ 3,  4],
       [ 5,  6]])

In [0]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
np.delete(a,5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [0]:
np.delete(a,1,axis=1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [0]:
np.delete(a,[0,2],axis=1)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])