In [0]:
import numpy as np

In [0]:
c = np.array([[0,1,2],[3,4,5]])                     #len() 행의 갯수  len([]) 열의 갯수 shape (n,m) n x m 행렬
c, len(c), len(c[0]), c.shape, type(c)

(array([[0, 1, 2],
        [3, 4, 5]]), 2, 3, (2, 3), numpy.ndarray)

In [0]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
d, d.shape, len(d), len(d[0]), len(d[0][0])

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]]), (2, 3, 4), 2, 3, 4)

In [0]:
a = np.arange(12)
a, a.shape, type(a)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,), numpy.ndarray)

In [0]:
b = a.reshape(3,4)                           #reshape : 배열 크기 변환
b, b.shape, type(b)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), (3, 4), numpy.ndarray)

In [0]:
a = np.array([[1,2,3],[4,5,6]])

In [0]:
a, a.T

(array([[1, 2, 3],
        [4, 5, 6]]), array([[1, 4],
        [2, 5],
        [3, 6]]))

In [0]:
# Indexing

In [0]:
b =np.array([[0,1,2], [3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
b[0][0]

0

In [0]:
b[0,1]

1

In [0]:
b[0][1]

1

In [0]:
b[-1,-1]

5

In [0]:
b[-1][-1]

5

In [0]:
x = np.array([[1,2],[3,4],[5,6]])                    #indexing
y = x[[0,1], [1,1]]

In [0]:
x, x.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]), (3, 2))

In [0]:
y, y.shape

(array([2, 4]), (2,))

In [0]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])                         #slicing
y = x[1:4, [1,2]]

In [0]:
x, x.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), (4, 3))

In [0]:
y, y.shape

(array([[ 4,  5],
        [ 7,  8],
        [10, 11]]), (3, 2))

In [0]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False,])

In [0]:
a[idx], a[a % 2 == 0]

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [0]:
x = np.array([[0,1,2], [np.nan, 4, 5], [6,7,8], [9,10,11]])
x, x[x>5], x[np.isnan(x)]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


(array([[ 0.,  1.,  2.],
        [nan,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]), array([ 6.,  7.,  8.,  9., 10., 11.]), array([nan]))

In [0]:
a = np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [0]:
a[0]

array([0, 1, 2, 3])

In [0]:
a[0, :]

array([0, 1, 2, 3])

In [0]:
a[0][:]

array([0, 1, 2, 3])

In [0]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [0]:
a[:2][:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [0]:
c = np.array([[0,1,2], [3,4,5]])
c, len(c), len(c[0]), c.shape, type(c), c.itemsize

(array([[0, 1, 2],
        [3, 4, 5]]), 2, 3, (2, 3), numpy.ndarray, 8)

In [3]:
d = np.array([2,3,4])
d, len(d), d.shape, type(d)

(array([2, 3, 4]), 3, (3,), numpy.ndarray)

In [0]:
c+d

array([[2, 4, 6],
       [5, 7, 9]])

In [0]:
# 최대/최소 : min, max, argmin, argmax
# 통계 : sum, mean(평균), median(중간값), str(표준편차), var(분산)

In [0]:
x=np.array([1,2,3,1])
x.sum(), x.max(), x.argmin(), x.argmax(), x.mean(), np.median(x), x.std()

(7, 3, 0, 2, 1.75, 1.5, 0.82915619758885)

In [0]:
x = np.array([[0,1,2],[7,8,9],[2,3,4],[4,5,6]])

In [0]:
x.sum(), x.max(), x.argmin(), x.argmax(), x.mean(), np.median(x), x.std()

(51, 9, 0, 5, 4.25, 4.0, 2.7118566825454966)

In [0]:
x = np.array([[1,3,5,7],[2,4,6,8]])

In [0]:
x, type(x), x.ndim, x.shape, len(x), x[0], x[:,3]

(array([[1, 3, 5, 7],
        [2, 4, 6, 8]]),
 numpy.ndarray,
 2,
 (2, 4),
 2,
 array([1, 3, 5, 7]),
 array([7, 8]))

In [0]:
x.sum(axis=0), x.sum(axis=1),x[0].sum(), x[:,3].sum()  #2차원 (axis = 0 : 두 행을 더함, axis = 1 : 각 행의 열끼리만 더함)

(array([ 3,  7, 11, 15]), array([16, 20]), 16, 15)

In [0]:
d = np.array([[[1,3,5],[5,6,7]],[[7,8,9],[10,11,12]]])
d, d.dtype, type(d), d.ndim, d.shape, len(d), d.sum(axis = 0), d.sum(axis = 1), d.sum(axis = 2)
                                               #3차원 axis = 0 (첫번째 행렬의 첫번째 행 + 두번째 행렬의 첫번째 행)
                                               #      axis = 1 (첫번째 행렬의 합 + 두번째 행렬의 합)
                                               #      axis = 2 (각 행의 합)

(array([[[ 1,  3,  5],
         [ 5,  6,  7]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 dtype('int64'),
 numpy.ndarray,
 3,
 (2, 2, 3),
 2,
 array([[ 8, 11, 14],
        [15, 17, 19]]),
 array([[ 6,  9, 12],
        [17, 19, 21]]),
 array([[ 9, 18],
        [24, 33]]))