In [0]:
import numpy as np

In [0]:
student_score =[
[1, 90, 80, 85, 0, 0.0, 0, 0],
[2, 88, 85, 90, 0, 0.0, 0, 0],
[3, 32, 85, 90, 0, 0.0, 0, 0],
[4, 42, 75, 93, 0, 0.0, 0, 0],
[5, 82, 86, 88, 0, 0.0, 0, 0]
]

student = np.array(student_score)

In [3]:
student

array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
       [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
       [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
       [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
       [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]])

In [4]:
student.shape

(5, 8)

In [0]:
#각 구성원 total, avg, min, max 필드 각 생성과 값 구하기
student[:,4] = np.sum(student[:,1:4], axis = 1)
student[:,5] = np.mean(student[:,1:4], axis = 1)
student[:,6] = np.min(student[:,1:4], axis = 1)
student[:,7] = np.max(student[:,1:4], axis = 1)

In [23]:
student

array([[  1.        ,  90.        ,  80.        ,  85.        ,
        255.        ,  85.        ,  80.        ,  90.        ],
       [  2.        ,  88.        ,  85.        ,  90.        ,
        263.        ,  87.66666667,  85.        ,  90.        ],
       [  3.        ,  32.        ,  85.        ,  90.        ,
        207.        ,  69.        ,  32.        ,  90.        ],
       [  4.        ,  42.        ,  75.        ,  93.        ,
        210.        ,  70.        ,  42.        ,  93.        ],
       [  5.        ,  82.        ,  86.        ,  88.        ,
        256.        ,  85.33333333,  82.        ,  88.        ]])

In [24]:
#학급 평균 구하기
np.mean(student[:,5], axis = 0)

79.4

In [9]:
#과목별 평균 구하기
np.mean(student[:,1:4], axis = 0)

array([66.8, 82.2, 89.2])